language: python
python:
    - 3.8

services:
    - docker

cache:
    - directories:
        - $HOME/miniconda

install:
    - travis_wait 30 docker build -t drop/drop .

    # conda installation
    - sudo apt update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    
    # Useful for debugging any issues with conda
    - conda info -a

    # install env
    - travis_wait 30 conda env create -f environment.yml
    - conda activate docker-drop

script:
    - drop demo 
    - sed "s|`pwd`/Output|/drop/analysis/Output|i" -i config.yaml
    - sed "s|`pwd`/Data|/drop/analysis/Data|i" -i config.yaml
    - sed "s|`pwd`/Data|/drop/analysis/Data|i" -i Data/sample_annotation.tsv
    
    - echo `pwd`
    - chmod -R o+rwX ./
    - chmod o+rX ../
    - chmod o+rX ../../
   
    - ls -la 

    - docker run -it --rm -v "`pwd`:/drop/" -v "`pwd`/Data:/drop/analysis/Data" -v "`pwd`/Output:/drop/analysis/Output" drop/drop snakemake -n
    - docker run -it --rm -v "`pwd`:/drop/" -v "`pwd`/Data:/drop/analysis/Data" -v "`pwd`/Output:/drop/analysis/Output" drop/drop snakemake --cores 4

    - ls -la

    - docker ps | grep -q drop


