language: python
python:
    - 3.8

services:
    - docker

cache:
    - directories:
        - $HOME/miniconda

install:
    - travis_wait 40 docker build -t drop/drop .

script:
    - docker run -it -v "volDROP:/drop/" drop/drop drop demo
    - docker run -it -v "volDROP:/drop/" drop/drop snakemake -n
    - docker run -it -v "volDROP:/drop/" drop/drop snakemake aberrantExpression --cores 4
    - docker run -it -v "volDROP:/drop/" drop/drop snakemake aberrantSplicing --cores 4
    - docker run -it -v "volDROP:/drop/" drop/drop snakemake exportCounts --cores 4
    - docker run -it -v "volDROP:/drop/" drop/drop snakemake mae --cores 4
    - docker run -it -v "volDROP:/drop/" drop/drop snakemake --cores 4


