name: drop

channels:
  - bioconda
  - conda-forge

dependencies:
  - snakemake
  - gatk4
  - samtools
  - tabix
  - bioconductor-outrider
  - bioconductor-fraser
  - bcftools
  - pandoc
  - graphviz
  - 
  - bioconductor-variantannotation
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
    #mumichae/tMAE TRUE
  - r-rmarkdown
  - r-knitr
  - r-ggplot2
  - r-ggthemes
  - r-cowplot
  - r-data.table
  - r-dplyr
  - r-tidyr
  - r-magrittr
  - r-devtools


